### ISSUE TITLE
Stopping after package build failure?

### ISSUE THREAD

**Issue by idontgetoutmuch** [cdepillabout/nix-reverse-deps-of-haskell-package#5]
@cdepillabout great for fixing this - thanks very much - it now runs but errors out when it fails to build a package. I somehow assumed I would get a list(?) of all packages that fail to build.

```
nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/19.09.tar.gz my.nix
```

```
let
  myHaskellPackageOverlay = self: super: {
    haskellPackages = super.haskellPackages.override {
      overrides = hself: hsuper: {
        random =
          let newRandomSrc = builtins.fetchGit {
                url = "https://github.com/idontgetoutmuch/random.git";
                rev = "4bb37cfd588996c55e62ec4f908b8ea7d99a38f6";
                ref = "interface-to-performance";
              };
          in
          # Since cabal2nix has a transitive dependency on random, we need to
          # get the callCabal2nix function from the normal haskellPackages that
          # is not being overridden.
          (import <nixpkgs> {}).haskellPackages.callCabal2nix "random" newRandomSrc { };
      };
    };
  };

  nixpkgs = import <nixpkgs> { overlays = [ myHaskellPackageOverlay ]; };
in
# This example derivation file is assumed to be in the current directory.  "./default.nix" is
# the current file you are looking at.
import ./default.nix {
  reverseDepsOf = "random";
  inherit nixpkgs;
}
```

**Comment by idontgetoutmuch** [comment]
[fail.log](https://github.com/cdepillabout/nix-reverse-deps-of-haskell-package/files/4248617/fail.log)

**Comment by cdepillabout** [comment]
@idontgetoutmuch Ah, yeah, this is actually a problem with `nix-build`.

By default, I believe that `nix-build` exits as soon as the first derivation fails to build.  You can change this with the `--keep-going` flag, which tells `nix-build` to not stop on the first failure, but to at least attempt to build as many derivations as possible.

In order to get a list of all failing derivations, I'd recommend you run the following:

```console
$ nix-build --keep-going -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/19.09.tar.gz my.nix
```

This will build through all derivations that it can, and then probably fail at the very end.

If you then run the same command again without `--keep-going`, it will first list all derivations it will try to build.

All of these derivations will _either_ be derivations that failed to build, _or_ transitive dependencies of derivations that failed to build.

For instance, in your `random` example, let's pretend that the `MonadRandom` package has a dependency on `random`, and then the `conduit` package has a dependency on both `MonadRandom` and `random`.

If `MonadRandom` fails to build because of a change in `random`, then _both_ `MonadRandom` and `conduit` should appear in the list of derivations that will be built when you run `nix-build` the second time.

(However, I think what you might be looking for is a list of exactly all the derivations that failed to build, _excluding_ the transitive dependencies of those derivations.  In the example above, that would be `MonadRandom`, but _not_ `conduit`.  I don't know an easy way to get this information.)

**Comment by idontgetoutmuch** [comment]
Ah sorry for the noise - I should have RTFM but the nix manual is hard.

Yes I would like to exclude the transitive dependencies but I am happy to live with what your excellent tool produces.

Thank you!
